builders:
  easyLocalizationGenerator:
    import: "package:sheet_loader_localization/sheet_builder.dart"
    builder_factories: ["localizationGenerator"]
    build_extensions: {".dart": [".localization_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]