name: sheet_loader_localization
description: Download an CSV file and generates the localization keys from an online Google Sheet.
version: 0.1.1
homepage: https://github.com/Hoang-Nguyenn
repository: https://github.com/Hoang-Nguyenn/sheet_loader_localization
issue_tracker: https://github.com/Hoang-Nguyenn/sheet_loader_localization/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.3.0
  build_config: ^1.0.0
  source_gen: ^1.2.2
  http: ^0.13.4
  path: ^1.8.1
  csv: ^5.0.1
  intl: ^0.17.0
  analyzer: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
